#BANNER
banner:
   charset: UTF-8
   location: banner.txt

server:
  port : 8081

spring:
   thymeleaf:
     cache: false
     check-template: true
     check-template-location: true
     content-type: text/html
     enabled: true
     encoding: UTF-8
     suffix: .html


#Postgres
#spring:
#   datasource:
#      url: jdbc:postgresql://localhost:5432/curso
#      username: postgres
#      password: 5432
#      initialization-mode: always
#      initialize: true
#      schema: #classpath:/schema.sql
#      continue-on-error: true

driver: org.postgresql.Driver
url: jdbc:postgresql://127.0.0.1:5432/curso
dbuser: postgres
dbpassword: 5432


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.show-sql=true






